all:
	cd trakt  && $(MAKE) && cd ..
	cd smtcoq && $(MAKE) && cd ..
	cd sniper && $(MAKE) && cd ..


install:
	cd trakt  && $(MAKE) install && cd ..
	cd smtcoq && $(MAKE) install && cd ..
	cd sniper && $(MAKE) install && cd ..
